version: '3.7'

services:

  composer:
    image: composer:2
    volumes:
      - ./:/root/weather
    working_dir: /root/weather

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command:
      - ./weather Warsaw
    volumes:
      - ./:/root/weather
    working_dir: /root/weather

